### ISSUE TITLE
Flux, Redux & cia.

### ISSUE THREAD

**Issue by czanella** [cassiozen/ReactCasts#13] opened 2016-11-16 12:44 UTC
I'd love to see a ReactCast about Flux, Redux & other ways to organize a big project that uses React. I like Flux & Redux and I understand the motivations behind them, but I'm not 100% sold on any of them.

Also, bug report: in IE9 + Windows Vista, the name of the channel appears as AngularCasts. Please fix.

**Comment by cassiozen** [comment] 2016-11-16 14:23
Thanks for the suggestion, @czanella.

As for your bug report: It's not a bug, it's a feature.

**Comment by cassiozen** [comment] 2017-07-10 23:10
Hey @czanella: Loved to see your suggestion here, but looks like nowadays everybody uses Redux without discussion... Maybe an episode about "when NOT to use redux would be more useful, but than again we already have [this](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367).

I'll close this issue for now, but please come up with new suggestions!

**Closed by cassiozen** 2017-07-10 23:10 UTC
Labels: Request a Screencast
